[package]
name = "whetstone"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
regex = "1.5.5"
